name: Print a single or all environment variables
on: push

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Check out repo        
        uses: actions/checkout@v2
      - run: echo " Print a single environment variable (the commit SHA ) - ${{ github.sha }} "
      - run: echo "Print all environment variables"
      - run:  env
